### ISSUE TITLE
It should list commits too

### ISSUE THREAD

**Issue by docteurklein** [tschaub/github-changelog#6]
Currently, the changelog is only done using http://mikedeboer.github.io/node-github/#issues.prototype.repoIssues .

Shouldn't we only (or too) use http://mikedeboer.github.io/node-github/#repos.prototype.getCommits ?

**Comment by jonataswalker** [comment]
Hi @tschaub is this alive? I mean, the project. I'd like to write a PR to address this feature. Particularly get `git tag` pushes.

**Comment by jonataswalker** [comment]
Never mind. There's another project (https://github.com/lalitkapoor/github-changes) that does this.

**Comment by tschaub** [comment]
@jonataswalker glad you found something that meets your needs.  I ran into issues with rate limiting and the GitHub API, so am not using this package.  It could be reworked to avoid using the GitHub API, but it looks like there are alternatives.

**Comment by jonataswalker** [comment]
All right, thanks for your response.
